#!/bin/bash
### BEGIN INIT INFO
# Provides:          cloud9
# Description:       A simple script which will start / stop cloud9 at boot / shutdown.
### END INIT INFO
# If you want a command to always run, put it here
# Carry out specific functions when asked to by the system
case "$1" in
  start)
    cd /root/c9sdk
    sudo nodejs server.js -p 8181 -l 0.0.0.0 -a : -w /media/NASDRIVE/workspace &
    #echo "Launching cloud9 with workspace root set to /media/NASDRIVE/workspace"
    ;;
  stop)
    echo "Stopping cloud9"
    # kill application you want to stop
    pkill -f "node ./server.js"
    ;;
  *)
    echo "Usage: /etc/init.d/cloud9 {start|stop}"
    exit 1
    ;;
esac
